CONTAINER_NAME=solsys
IMAGE_NAME=solsys
IMAGE_TAG=dev
DOCKERFILE_PATH="./"

OPTIONS="-it --rm -p 3000:3000 -p 5000:5000"
COMMANDS=""
ARGS=""

docker build -t $IMAGE_NAME:$IMAGE_TAG $DOCKERFILE_PATH
docker run $OPTIONS $IMAGE_NAME:$IMAGE_TAG $COMMANDS $ARGS
